### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by drew202k** [Tyson3101/Auto-Youtube-Shorts-Scroller#10] opened 2023-03-25 06:12 UTC
tried reinstalling it, but to no avail, it's not working, I even tried with google chrome and Microsoft edge they are not working as intended.

I tried refreshing the page, closing the app, close the browser. not working

**Comment by Tyson3101** [comment] 2023-03-25 09:18
Yeah you aren't the only one
I can't replicate this issue on my own so if you could help by telling me:
- If you see any errors that could be helpful in the console
- Any settings you have configured for the extension
- Or anything else you deem helpful

That would be appreciated 
and thanks for the issue

**Comment by drew202k** [comment] 2023-03-25 15:06
I really don't know  how to replicate its just this add on stop working

**Comment by Tyson3101** [comment] 2023-03-30 12:10
Yo, Are you able to tell me if you are still facing the issue. I believed I updated a fix

**Comment by drew202k** [comment] 2023-03-30 12:39
still not working :(

**Comment by Vittel26** [comment] 2023-03-30 17:44
doesn't work for me either, also tried updating but still doesn't work

**Comment by drew202k** [comment] 2023-03-31 01:32
![image](https://user-images.githubusercontent.com/128885333/229000381-21d51f2e-b4f4-4f9d-b8c7-d2f16aab0551.png)

**Comment by Seathre** [comment] 2023-04-01 16:51
```
content.js:146 Uncaught TypeError: Cannot read properties of null (reading 'innerText')
    at checkIfVaildVideo (content.js:146:9)
    at checkForNewShort (content.js:64:14)
checkIfVaildVideo @ content.js:146
checkForNewShort @ content.js:64
```

Also not working for me. Receiving the above error in console.

**Comment by Tyson3101** [comment] 2023-04-02 02:21
Thanks for the help, I have started to get that too, and I have fixed that error (may have been a silly one), so in a day or two, once google reviews my update, I hope it will be fixed. 

And I appreciate all your patience and trying to help/alert me of the extension being broken

**Comment by Seathre** [comment] 2023-04-02 02:26
Best of luck, and thanks for your work on this.

**Comment by Tyson3101** [comment] 2023-04-03 11:27
Hi, The extension has been updated and looks all good on my end.
If face any other issues check if updated to v 2.2.2

**Comment by LegoMamn** [comment] 2023-04-03 11:56
> Hi, The extension has been updated and looks all good on my end. If face any other issues check if updated to v 2.2.2

I updated and did tons of refresh and it works thank you

**Comment by Seathre** [comment] 2023-04-03 14:04
Updated on the Chrome Web Store, appears to be working as intended. 🙂

**Closed** 2023-04-03 21:30 UTC
